CREATE TABLE CURRENTPRICE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    encu VARCHAR(50) DEFAULT NULL,
    chcu VARCHAR(50) DEFAULT NULL,
    rate_float REAL DEFAULT NULL,
    update_time VARCHAR(50)
);